---
- name: Install ArgoCD
  hosts: localhost
  tasks:
    - name: Download ArgoCD manifest
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        dest: /tmp/argocd-install.yaml

    - name: Ensure ArgoCD namespace exists
      ansible.builtin.command:
        cmd: kubectl apply -f -
      args:
        stdin: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: argocd

    - name: Apply ArgoCD manifest to Kubernetes
      ansible.builtin.command:
        cmd: kubectl apply -n argocd -f /tmp/argocd-install.yaml

    - name: Wait for ArgoCD server to become available
      ansible.builtin.command:
        cmd: kubectl wait --for=condition=available --timeout=300s deployment/argocd-server -n argocd
      register: wait_result
      failed_when: "'condition met' not in wait_result.stdout"

    - name: Patch ArgoCD server service to NodePort
      ansible.builtin.command:
        cmd: >
          kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'

    - name: Get ArgoCD initial admin password
      ansible.builtin.shell: |
        cmd: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d > argocd-admin-password.txt
      register: admin_password

    - name: Display ArgoCD admin password
      ansible.builtin.debug:
        msg: "ArgoCD initial admin password is {{ admin_password.stdout }}"